import Link from 'next/link';
import type { ReactNode } from 'react';
import { META_INFERENCE_CODE, META_MODEL_CODE, META_REPOSITORY, META_REVISION, METATRAY_ADAPTER_CODE, METATRAY_CHAIN_CODE, METATRAY_REPOSITORY, PONS_CURVE_CODE, PONS_FACTORY_CODE, PONS_LAUNCH_CODE, PONS_POOL_MANAGER_CODE, PONS_REPOSITORY, PONS_REVISION } from './sources';

export type InformationSlug = 'about' | 'experiment' | 'science' | 'how-it-works' | 'deployment' | 'terms' | 'privacy' | 'evidence' | 'lore';
type Information = {
  eyebrow: string; title: string; intro: string; note?: string;
  sections: { id: string; title: string; body: ReactNode }[];
  next: { href: string; label: string };
};

function External({ href, children }: { href: string; children: ReactNode }) {
  return <a href={href} target="_blank" rel="noreferrer">{children}</a>;
}

function Contact() {
  let href: string | null = null;
  try {
    const url = new URL(process.env.METATRAY_PUBLIC_CONTACT_URL ?? '');
    if (url.protocol === 'https:' && !url.username && !url.password) href = url.href;
  } catch { /* A private contact destination has not been configured. */ }
  return href ? <p>For questions about these policies or a private request, use the <External href={href}>operator’s contact channel</External>. Never send a wallet seed phrase, signing key or account password.</p>
    : <p>A private contact channel has not yet been configured for this deployment. Do not post sensitive information in public repository issues. The deployment operator must provide any contact information required by applicable law.</p>;
}

export const informationPages: Record<InformationSlug, Information> = {
  experiment: {
    eyebrow: 'Experiment 001', title: 'Let the market become an experience.',
    intro: 'MetaTray observes confirmed Pons token trades, translates a bounded market window into sight, sound and language, and records how Meta TRIBE v2 predicts a cortical response to that authored stimulus.',
    note: 'Market pulses can be live before model inference is connected. They are labelled inputs, not brain output. Trading remains paper-only.',
    sections: [
      { id: 'question', title: 'The question', body: <><p>What happens inside a released cortical-response model when a token market is turned into an audiovisual experience? MetaTray makes that question inspectable. A trade is never sent directly into a “brain.” Confirmed public events first become a declared video, audio and language treatment. The model then predicts an averaged-subject fMRI response to that sensory material.</p><p>The experiment is deliberately narrower than predicting price, measuring a trader’s mind or proving that a token has feelings. It connects a public market record to a reproducible stimulus and a separately verifiable model result.</p></> },
      { id: 'pons', title: '01 · Pons writes the live record', body: <><p>The direct observer asks the configured chain for the factory that created this project’s token. In Pons v2 mode it verifies deployed bytecode, discovers the launch curve, hook and V4 PoolManager, and follows confirmed curve or graduated-pool swaps. It preserves the chain ID, transaction hash, block hash, log index, raw amounts and decoded direction.</p><p>A successful RPC response with no matching swaps is shown as <strong>connected and waiting</strong>. Missing configuration, a wrong chain, an unavailable provider, stale blocks or changing block hashes are shown as degraded states. None of those states silently create demo trades.</p><div className="article-table"><table><thead><tr><th>Visible state</th><th>What it establishes</th><th>What it does not establish</th></tr></thead><tbody><tr><td>Market pulse</td><td>A decoded confirmed buy or sell was received</td><td>That the model ran</td></tr><tr><td>Transaction receipt</td><td>The event can be traced to its public source</td><td>The identity or intention of a trader</td></tr><tr><td>Connected · waiting</td><td>The observer reached the configured market</td><td>That a trade occurred in the recent window</td></tr></tbody></table></div></> },
      { id: 'translation', title: '02 · The record becomes sensory input', body: <><p>A retained market window is rendered as three synchronized channels: a moving market-screen video, declared trade tones and factual spoken context. The input has a cutoff, so a later trade cannot be inserted into an earlier job. Its market events, text, timing and rendered-media hash become part of the experiment receipt.</p><p>This translation is an authored treatment. Chart scale, colors, language, voice and sound design can affect a multimodal model even when the underlying trades are unchanged. MetaTray therefore exposes those choices instead of presenting them as a natural psychological meaning of buying or selling.</p></> },
      { id: 'cortex', title: '03 · The cortical echo arrives later', body: <><p>The separately hosted GPU worker loads pinned TRIBE and feature-model revisions, extracts the official language, vision and audio features, and calls the released prediction interface. A result is accepted only after its shape and finite values pass validation. The website colors the anatomical surface from those returned values and archives the result as a cortical epoch.</p><p>The market clock and inference clock remain separate. A cyan or coral receipt particle can appear immediately outside the surface after an observed trade; the predicted surface changes only when an actual worker result is published. Camera rotation is presentation motion and proves neither event.</p></> },
      { id: 'paper', title: '04 · The model may inform a paper rule', body: <><p>MetaTray does not give TRIBE a wallet and TRIBE does not output trade orders. The observer policy holds simulated cash. The momentum comparison uses an authored market rule. The cortical paper policy keeps that market direction and only uses a fresh predicted-response-change magnitude to scale simulated exposure.</p><p>Every fill remains a paper entry with estimated fees and slippage. The application has no private-key field, signing flow, custody path or transaction submission code. A predicted response is not evidence of investment conviction, future returns or a profitable edge.</p></> },
      { id: 'live-connection', title: 'Connect Experiment 001 to the new token', body: <><p>Set the following values as <strong>server-side Production variables in Vercel</strong>, then redeploy the latest <code>main</code>. Use the new MetaTray token’s own verified deployment facts. The RPC value is private and must never be committed or prefixed with <code>NEXT_PUBLIC_</code>.</p><pre className="article-code"><code>{`METATRAY_MODE=live\nMETATRAY_FEED=rpc\nRPC_HTTP_URL=<private HTTP RPC endpoint>\nCHAIN_ID=<numeric EVM chain ID>\nTOKEN_ADDRESS=<new MetaTray token contract>\nMARKET_PROTOCOL=pons-v2\nPONS_FACTORY_ADDRESS=<verified factory on that chain>\nBLOCK_EXPLORER_URL=<optional public HTTPS explorer>`}</code></pre><p>This recent-swap mode needs no database, model token or Python service. The complete cortical experiment additionally needs Postgres, the persistent indexer and an authorized GPU worker; those services are connected through indexed mode and cannot be created by a browser animation.</p></> },
      { id: 'proof', title: 'What counts as a completed run', body: <ol><li>The website reports the intended chain and token rather than fallback labels.</li><li>A displayed swap matches its public transaction receipt, raw amounts, direction and confirmed block.</li><li>The stimulus receipt names the exact input window, generated media and cutoff.</li><li>A model result identifies immutable code, weights and feature revisions plus its processing time and output hash.</li><li>The cortical surface changes from returned model values, while stale or missing output stays explicitly labelled.</li><li>Any paper decision occurs only after publication and retains the rule, inputs and simulated costs.</li></ol> },
      { id: 'evidence', title: 'Inspect the experiment', body: <div className="article-source-list"><External href={METATRAY_CHAIN_CODE}>Pons and chain decoding code</External><External href={`${METATRAY_REPOSITORY}/blob/main/services/tribe/renderer.py`}>Market stimulus renderer</External><External href={METATRAY_ADAPTER_CODE}>MetaTray TRIBE adapter</External><External href={META_INFERENCE_CODE}>Pinned Meta inference implementation</External><Link href="/evidence">Code and evidence map</Link><Link href="/science">Scientific meaning and limitations</Link></div> }
    ], next: { href: '/', label: 'Open the live observatory' }
  },
  lore: {
    eyebrow: 'The MetaTray lore', title: 'The market dreams in public.',
    intro: 'Every confirmed trade becomes part of an experience. Every completed model run leaves a cortical epoch. MetaTray turns that sequence into a public, inspectable mythology without pretending the model is alive.',
    note: 'The lore names real system states. “Pulse” means an observed market input. “Cortical epoch” means a completed TRIBE prediction. “Memory” means a retained receipt and atlas entry.',
    sections: [
      { id: 'silence', title: 'Before the first signal', body: <><p>MetaTray begins as a dark, uncoloured cortical surface. It has no market memory and no predicted response. The empty cortex is called <strong>the Silence</strong>: a visible statement that nothing has arrived and nothing has been inferred.</p><p>The first confirmed transaction ends the Silence. Its chain, block, hash, direction and raw amounts enter the public feed. That event is the origin of the experiment, not the birth of a conscious being.</p></> },
      { id: 'pulse', title: 'The Pulse', body: <><p>A buy arrives as a cyan particle. A sell arrives as a coral particle. This <strong>Pulse</strong> stays outside the cortical surface, is tied to a receipt, and lets observers follow the event back to its public source.</p><p>The Pulse is MetaTray’s authored signal language. It says that the market changed; it does not claim that a human brain felt excitement, fear or pain.</p></> },
      { id: 'translation', title: 'The Translation', body: <><p>A bounded window of trades is translated into three sensory channels: a moving market screen, declared trade tones and factual spoken context. Together they form <strong>the Experience</strong>. Its cutoff prevents later trades from being inserted into an earlier stimulus.</p><p>This is where numbers acquire sensory form. The translation rules are part of the experiment and remain inspectable in the source and result manifest. Different visual, sound or language choices could produce different predictions.</p></> },
      { id: 'two-clocks', title: 'The market moves now. The model answers later.', body: <><p>MetaTray operates on two clocks. The market clock records confirmed on-chain events and can pulse immediately. The inference clock waits for a complete stimulus, feature extraction and GPU processing.</p><p>Keeping both clocks visible is part of the experiment. A market animation never masquerades as model inference, and a completed result always carries the cutoff and publication time.</p></> },
      { id: 'echo', title: 'The Cortical Echo', body: <><p>The external GPU worker presents the Experience to Meta TRIBE v2. The returned surface values predict an averaged subject’s fMRI response to that authored material. MetaTray calls the completed result <strong>the Cortical Echo</strong>.</p><p>The Echo arrives after preprocessing and inference. It is the model’s response to a completed sensory window, rather than an instantaneous reaction or a price forecast. Only this returned numeric result colors the anatomical fsaverage5 surface as model output.</p></> },
      { id: 'epochs', title: 'The Epochs become memory', body: <><p>Each valid Echo is sealed as a <strong>Cortical Epoch</strong>. The receipt binds its market window, stimulus hash, model revision, output hash, publication time and surface dimensions. Orphaned chain history invalidates dependent work instead of becoming legend.</p><p>Epochs accumulate in <strong>the Cortical Chronicle</strong>. Calm periods, rallies, selloffs and active windows can be revisited as named market regimes, while the raw trade count, volume and price change remain beside the response statistic. The chronicle is MetaTray’s memory because it is an archive of reproducible records.</p></> },
      { id: 'observer', title: 'The Observer watches the loop', body: <><p>The paper agent sits beside the market and the cortical sequence. In observer mode it holds simulated cash. Comparison policies can study momentum or use a fresh response-change magnitude to scale an authored paper rule.</p><p>The Observer never turns TRIBE into an oracle. The model supplies predicted sensory response; the market rule supplies financial direction. Every fill remains simulated and names the event and model result that were available when the decision was recorded.</p></> },
      { id: 'canon', title: 'The canon', body: <div className="article-table"><table><thead><tr><th>Name</th><th>Real system state</th></tr></thead><tbody><tr><td>The Silence</td><td>No confirmed market input and no model result</td></tr><tr><td>The Pulse</td><td>A confirmed buy or sell entering the live visualization</td></tr><tr><td>The Experience</td><td>The exact market-derived video, audio and narration supplied to the model</td></tr><tr><td>The Cortical Echo</td><td>A validated TRIBE prediction published after processing</td></tr><tr><td>A Cortical Epoch</td><td>One completed result plus its immutable provenance receipt</td></tr><tr><td>The Cortical Chronicle</td><td>The retained sequence of completed epochs</td></tr><tr><td>The Observer</td><td>The transparent paper-only policy layer</td></tr></tbody></table></div> },
      { id: 'truth', title: 'The rule that keeps the lore real', body: <><p>Every dramatic word maps to evidence. A Pulse needs a transaction receipt. An Echo needs an actual model output. An Epoch needs matching input and output hashes. When a service is absent, MetaTray shows the Silence or a waiting state.</p><p>MetaTray is an independent project using released Meta research software. The name and story do not indicate that Meta operates, sponsors or endorses the project or an associated token.</p></> }
    ], next: { href: '/', label: 'Watch the sequence live' }
  },
  evidence: {
    eyebrow: 'Code & evidence', title: 'Inspect the code. Verify the data.',
    intro: 'Follow the actual implementation from a decoded transaction to an audiovisual input and, when the GPU pipeline is running, a Meta TRIBE v2 result.',
    note: 'A source-code link proves where an implementation lives. A real inference claim also requires a completed result and its matching input/output receipt.',
    sections: [
      { id: 'repositories', title: 'The source repositories', body: <><p><External href={METATRAY_REPOSITORY}>MetaTray — fourtyeightTech/metabrain</External> contains this website, the chain adapters, rendering pipeline, model adapter and paper engine.</p><p><External href={META_REPOSITORY}>Meta — facebookresearch/tribev2</External> is the original released research implementation. <External href={PONS_REPOSITORY}>Pons — ponsdotdev/ponsfamily</External> is the protocol source used to audit the launch-record, curve and graduated-pool interfaces. These references identify independent upstream projects and do not imply sponsorship or partnership.</p></> },
      { id: 'actual-code', title: 'The code that runs the experiment', body: <ul><li><External href={METATRAY_CHAIN_CODE}>MetaTray chain decoder</External>: reads curve/pool events and preserves transaction hashes, block hashes, log indexes and raw token amounts.</li><li><External href={PONS_LAUNCH_CODE}>Pinned Pons launch interface</External>, <External href={PONS_FACTORY_CODE}>factory</External>, <External href={PONS_CURVE_CODE}>curve</External> and <External href={PONS_POOL_MANAGER_CODE}>V4 PoolManager event</External>: the immutable protocol sources matched by the adapter.</li><li><External href={METATRAY_ADAPTER_CODE}>MetaTray model adapter</External>: imports <code>TribeModel</code>, prepares events from the rendered video and calls <code>model.predict</code>.</li><li><External href={`${METATRAY_REPOSITORY}/blob/main/services/tribe/renderer.py`}>MetaTray stimulus renderer</External>: constructs the market video and narrated input.</li><li><External href={META_INFERENCE_CODE}>Meta inference implementation</External>: the upstream pretrained-model and audiovisual prediction interface.</li><li><External href={META_MODEL_CODE}>Meta model architecture</External>: the released encoding model.</li></ul> },
      { id: 'provenance', title: 'Pinned upstream implementations', body: <><p>The model adapter requires Meta source revision <code>{META_REVISION}</code>. The audited Pons interface references use revision <code>{PONS_REVISION}</code>. Those links are immutable; downloaded TRIBE weights and feature models have their own immutable revisions in a completed result manifest.</p><p>MetaTray source links point to its main branch. Check the deployed build’s Git revision against that branch before assuming both contain the same code. A source match is still not a live-chain receipt or a completed model run.</p></> },
      { id: 'market-proof', title: 'Evidence for real market data', body: <><p>The live input stream shows the chain, confirmed block window, successful read time and decoded swaps. Open an event to inspect its transaction hash, block hash, log index, raw amounts and price basis. If an explorer is configured, the receipt links to the transaction.</p><p>Direct RPC mode re-reads a bounded recent window and does not maintain a durable paper account or queue model jobs. Indexed mode supplies the persistent event history, paper ledger and GPU queue. A connected provider with no matching swaps is shown as waiting, not populated with invented trades.</p></> },
      { id: 'model-proof', title: 'Evidence for an actual Meta result', body: <><p>Require a completed prediction receipt with its source window, model and feature revisions, stimulus hash, output hash, input age and processing latency. Match those hashes to the retained worker artifacts. The fsaverage5 surface must match the returned vertex order and dimensions.</p><p>The market-input animation is an authored visualization of observed buys and sells. It is not a cortical prediction. Only a returned TRIBE result is labelled model output; stale results are labelled delayed. The research release predicts fMRI responses to sensory stimuli, not token prices or trading success.</p><p>The released Meta code and weights are CC BY-NC 4.0. The deployment still needs a rights basis for its intended use and a separately configured GPU worker.</p></> }
    ], next: { href: '/deployment', label: 'Connect a real feed' }
  },
  about: {
    eyebrow: 'About MetaTray', title: 'A market you can observe. A response you can inspect.',
    intro: 'MetaTray connects token-market observations to an experiment in predicted cortical responses, using an integration with Meta’s TRIBE v2 research software.',
    sections: [
      { id: 'the-idea', title: 'What MetaTray is', body: <><p>A token trade changes a market. MetaTray records that change, builds an audiovisual description of it, and can present the resulting experience to a cortical-response model. The website brings the market, the sensory input, the predicted surface and a simulated account into one observatory.</p><p>The experiment is about an inspectable relationship between an input and a model output. A completed prediction has a source window, model revision, processing time and receipt. You can see what was observed and what was generated from it.</p></> },
      { id: 'meta-research', title: 'Built around Meta’s research', body: <><p>The model integration uses <External href="https://github.com/facebookresearch/tribev2">Meta TRIBE v2</External>. Its released inference interface predicts fMRI responses to video, sound and language. MetaTray supplies market-derived sensory material to that interface.</p><p>Meta supplies the upstream model architecture and research implementation. MetaTray supplies the chain adapter, stimulus construction, provenance records, visualization and paper-trading experiment. These additions are this project’s work; the financial application is not an established result from the model release.</p><p>MetaTray is an independent project. Model attribution does not mean Meta created, operates, sponsors or endorses MetaTray or any associated token.</p></> },
      { id: 'experience', title: 'What you can explore', body: <ul><li><strong>The market:</strong> observed trades, direction, quote volume and a price history.</li><li><strong>The stimulus:</strong> a factual preview of the sensory input constructed from a recorded market window.</li><li><strong>The cortex:</strong> a rotatable 3D surface, with actual model values only when a completed result is available.</li><li><strong>The atlas:</strong> completed cortical epochs paired with the trade count, volume, price change and descriptive regime from their exact market windows.</li><li><strong>The account:</strong> simulated cash, positions, fees and decisions, with an explicit policy label.</li><li><strong>The receipts:</strong> downloadable JSON, a visual share card and a direct completed-result link.</li></ul> },
      { id: 'operating-modes', title: 'Demo and connected research', body: <><p>The default live mode shows connection instructions until a real market is configured. A direct RPC observer reads recent swaps without a database. Explicit demo mode is available separately with labelled synthetic trades and no model predictions.</p><p>Persistent paper accounts and actual model results use a separately configured chain indexer, database and GPU worker. A live market feed can operate before the model service is ready. The interface keeps market availability and prediction availability separate.</p><p>Real model output requires access to the upstream weights and an appropriate rights basis. A deployed website alone does not activate TRIBE.</p></> },
      { id: 'boundaries', title: 'The boundaries of the experiment', body: <><p>MetaTray does not measure a visitor’s brain, read a trader’s thoughts or establish that the model feels anything. It does not claim to predict token prices, identify buyer emotions or produce profitable trading decisions.</p><p>The current account is paper-only. This application has no signing-key input, custody service or order-submission path. Any token purchase made on a separate service is outside this simulation.</p><p>Read <Link href="/science">the science</Link> for the model’s meaning and limitations, and <Link href="/terms">the terms</Link> before relying on the service.</p></> }
    ], next: { href: '/how-it-works', label: 'Follow a trade through MetaTray' }
  },
  science: {
    eyebrow: 'Meta TRIBE v2', title: 'The science behind the surface.',
    intro: 'MetaTray integrates a model of cortical responses to sensory experiences. Understanding the input, the output and the limits is part of understanding what the 3D view means.',
    note: 'Demo mode displays illustrative geometry. A model prediction is shown only when the configured worker publishes a real result.',
    sections: [
      { id: 'model', title: 'What TRIBE v2 predicts', body: <><p>TRIBE v2 is Meta’s multimodal brain-encoding model. The released inference interface accepts audiovisual or language-derived stimuli and returns predicted fMRI responses on a cortical surface for an averaged subject. This is a prediction of a measured-signal target, rather than a simulation of individual biological neurons.</p><p>MetaTray calls the released <code>TribeModel</code> interface from its separate Python worker. It does not substitute a language-model description for a numeric cortical prediction.</p></> },
      { id: 'inputs', title: 'Three kinds of sensory input', body: <><p>The model combines representations of language, vision and audio. The integration pins the checkpoint and feature-model revisions so a receipt can identify the software and weights behind a result.</p><div className="article-table"><table><thead><tr><th>Channel</th><th>Upstream feature model</th><th>MetaTray input</th></tr></thead><tbody><tr><td>Language</td><td>Llama 3.2 3B</td><td>Factual spoken market context with aligned word timing</td></tr><tr><td>Vision</td><td>V-JEPA 2</td><td>A generated market-screen video</td></tr><tr><td>Audio</td><td>w2v-BERT 2.0</td><td>Narration and declared trade tones</td></tr></tbody></table></div><p>A choice of colors, sounds or words changes the stimulus. These are authored experimental choices, not an intrinsic translation from a buy or sell into a human psychological state.</p></> },
      { id: 'surface', title: 'Reading the 3D surface', body: <><p>The integration prepares the fsaverage5 surface with 20,484 vertices across two hemispheres. Those are locations used to display model output; they are not a count of neurons or a reconstructed human connectome.</p><p>For actual predictions, cyan marks positive normalized model values and coral marks negative values on a fixed symmetric display scale. Neither color means happiness, fear, profit or loss. The response trace summarizes magnitude across surface values.</p><p>Without model output, fresh real swaps create separate exterior particles: cyan for buys and coral for sells. That is an authored market-input mapping, not a Meta prediction. Camera rotation and manual dragging never alter model values.</p></> },
      { id: 'timing', title: 'Timing and uncertainty', body: <><p>Market observations and model publication run on different clocks. The page polls direct RPC snapshots every five seconds, or indexed snapshots every two seconds, while active. Observed trades also wait for the configured confirmation depth. The default worker configuration queues a rolling context of up to 100 seconds at a 15-second interval. Those intervals describe the application’s configuration, not a guaranteed inference speed.</p><p>The released model can use context within the supplied window. MetaTray restricts each job to observations available at its cutoff and retains upstream temporal alignment. Preprocessing, feature extraction and GPU inference add delay. The receipt records when the input ended and when the result became available.</p><p>Paper decisions use a prediction only after it has been published and while it satisfies the configured freshness limit. Delayed results can remain visible for inspection without authorizing a new cortical paper decision.</p></> },
      { id: 'financial-experiment', title: 'What the trading rule adds', body: <><p>TRIBE does not output an order or a forecast of market returns. MetaTray’s cortical paper policy uses the magnitude of predicted-response change to scale an authored momentum exposure rule. The direction still comes from a market rule.</p><p>A stronger response does not establish stronger investment conviction. This market application is experimental and has not been financially validated by this project. The observer and momentum policies provide explicitly labelled comparisons.</p></> },
      { id: 'rights', title: 'Attribution and model rights', body: <><p>The released TRIBE source and checkpoint use CC BY-NC 4.0. Their terms and the separate terms of feature models still apply. This repository provides integration code and references; it does not distribute the TRIBE checkpoint or grant a commercial model license.</p><p>A free interface does not automatically make token-related model use noncommercial. The operator needs an appropriate rights basis before enabling that use. Attribution to Meta identifies the research source and does not establish an endorsement.</p></> },
      { id: 'sources', title: 'Read the original sources', body: <div className="article-source-list"><External href="https://github.com/facebookresearch/tribev2">Meta TRIBE v2: official code and inference interface</External><External href="https://huggingface.co/facebook/tribev2">Official checkpoint and model card</External><External href="https://github.com/facebookresearch/tribev2/blob/main/LICENSE">Upstream source license</External><External href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0 terms</External><External href="https://github.com/fourtyeightTech/metabrain/blob/main/docs/SCIENCE.md">MetaTray’s detailed scientific integration notes</External></div> }
    ], next: { href: '/how-it-works', label: 'See the complete data path' }
  },
  'how-it-works': {
    eyebrow: 'From trade to response', title: 'One observation. An inspectable chain of events.',
    intro: 'MetaTray keeps the market feed, the constructed experience, the predicted response and the paper decision connected through explicit records.',
    sections: [
      { id: 'observe', title: 'Observe the configured token', body: <><p>The direct RPC observer reads a bounded recent window on the selected chain; the persistent indexer adds durable history, paper state and inference jobs. Both use the operator’s selected token and verified protocol contracts. It records mined trade events, token direction, normalized amounts and their source block. The Pons V2 adapter covers its curve and derived graduated pool; a separate adapter supports an explicitly selected compatible V3 pool.</p><p>Public receipts identify the chain, transaction hash, log index and block hash. The system does not infer the real-world identity of a trader. No token or network is silently borrowed from another project.</p></> },
      { id: 'construct', title: 'Construct the experience', body: <><p>A bounded window of observations becomes a generated screen recording, trade tones and factual narration. The worker renders actual video and audio files. The input explains the market in the configured quote asset rather than assuming every value is US dollars.</p><p>The same window also provides the source data for the on-screen stimulus preview. The complete job receipt identifies the exact generated media by its hash.</p></> },
      { id: 'predict', title: 'Run the Meta model', body: <><p>The GPU worker loads an explicitly configured TRIBE installation and checkpoint. It extracts events from the rendered media through the official interface, runs the model, validates the output dimensions and stores a prediction with its software and data provenance.</p><p>If the worker is unavailable, the model lacks access or output validation fails, the website does not invent a replacement prediction. A live market feed may continue while the cortical view waits.</p></> },
      { id: 'display', title: 'Publish a visible result', body: <><p>The read API delivers the published result and its anatomical surface to the browser. The cortex colors update from the returned model values. A response trace and input-age label help distinguish current output from a delayed result.</p><p>Each completed result enters the cortical atlas with summary statistics derived from the immutable job input. Visitors can reopen that epoch, copy its direct result link, download the complete JSON receipt or export a visual receipt with the current 3D surface and public hashes.</p><p>Market updates can be frequent while model inference remains asynchronous. The moving camera is independent of both. Each state is labelled so visual motion is not confused with neural change.</p></> },
      { id: 'paper', title: 'Compare paper policies', body: <div className="article-table"><table><thead><tr><th>Policy</th><th>What it uses</th><th>When it acts</th></tr></thead><tbody><tr><td>Observer</td><td>Market observations</td><td>Holds cash without simulated orders</td></tr><tr><td>Momentum</td><td>A 30-second market comparison</td><td>An authored threshold and cooldown</td></tr><tr><td>Cortical</td><td>Momentum plus predicted-response-change magnitude</td><td>Only after a real, fresh prediction has been published</td></tr></tbody></table><p>All fills remain simulated. Fees, slippage, cash, position and cost basis are accounted for by the paper engine. Simulated returns are not a promise about live execution.</p></div> },
      { id: 'audit', title: 'Inspect and reproduce', body: <><p>Open a market event to inspect its receipt. Export a session to retain the displayed observations and any available prediction. The source repository documents model versions, receipt fields, queue behavior and the paper rule.</p><p>A chain reorganization can invalidate source events. The indexer’s rollback logic removes affected jobs and results and restores the corresponding paper state. Provider-specific recovery behavior still needs acceptance testing on the selected live deployment.</p></> }
    ], next: { href: '/science', label: 'Understand the model’s limits' }
  },
  deployment: {
    eyebrow: 'Model setup', title: 'Connect the market. Then the model.',
    intro: 'Start with real market swaps through a server-side RPC connection on Vercel. Add the persistent indexer, database and GPU worker to run the full Meta TRIBE experiment.',
    sections: [
      { id: 'website', title: 'Start with the website', body: <><p>Import <code>fourtyeightTech/metabrain</code> into Vercel as a Next.js application. Keep the root directory at <code>.</code>, use <code>npm ci</code> to install and <code>npm run build</code> to build. Set <code>METATRAY_MODE=live</code> and <code>METATRAY_FEED=rpc</code>.</p><p>Add server variables <code>RPC_HTTP_URL</code>, <code>CHAIN_ID</code>, <code>TOKEN_ADDRESS</code>, <code>MARKET_PROTOCOL=pons-v2</code> and <code>PONS_FACTORY_ADDRESS</code>. Use this project’s verified contracts. For a compatible V3 pool, choose <code>MARKET_PROTOCOL=uniswap-v3</code> and supply <code>V3_POOL_ADDRESS</code> instead of the factory. Keep RPC credentials private; never prefix them with <code>NEXT_PUBLIC_</code>.</p><p>Redeploy after changing variables. No database or model download is needed for this recent-swap view. Missing settings appear in the feed console. Optional <code>BLOCK_EXPLORER_URL</code> adds transaction links. Synthetic previews require an explicit <code>METATRAY_MODE=demo</code>.</p></> },
      { id: 'chain', title: 'Add persistent history and model jobs', body: <><p>Provision Postgres and run the supplied migration. Configure the actual chain ID, token, start block and verified protocol addresses. Run the Node indexer on a persistent host. The repository’s environment template and doctor command describe the required inputs.</p><p>Verify a real swap against its transaction receipt. Switch the website to <code>METATRAY_FEED=indexed</code> and supply a limited <code>DATABASE_READ_URL</code>. Keep worker credentials private. This enables the persistent paper ledger and optional GPU job queue; the direct RPC observer has neither.</p></> },
      { id: 'gpu', title: 'Prepare the Meta worker', body: <><p>Establish the rights basis for the intended model use, obtain access to the required feature models and select immutable checkpoint revisions. Prepare the model volume and start the supplied Python service on a suitable GPU host.</p><p>The integration imports <code>TribeModel</code>, constructs events from <code>stimulus.mp4</code>, and calls the upstream prediction interface. Run the operator smoke test and measure real processing latency before treating the connection as ready.</p><p>Vercel does not host this persistent GPU workload. Setting a website environment variable alone cannot produce a cortical prediction.</p></> },
      { id: 'acceptance', title: 'Check the complete connection', body: <ol><li>Confirm the observed token and quote asset are correct.</li><li>Match an event to its source transaction and block.</li><li>Inspect the generated audiovisual input and its cutoff.</li><li>Verify a completed model result, surface dimensions and provenance.</li><li>Check freshness labels, outage behavior and the paper rule.</li><li>Review the public terms, private contact route and actual data practices before launch.</li></ol> },
      { id: 'instructions', title: 'Deployment references', body: <div className="article-source-list"><External href="https://github.com/fourtyeightTech/metabrain/blob/main/AGENT_HANDOFF.md">Ordered deployment handoff</External><External href="https://github.com/fourtyeightTech/metabrain/blob/main/docs/DEPLOYMENT.md">Environment and service configuration</External><External href="https://github.com/fourtyeightTech/metabrain/blob/main/docs/VERIFICATION.md">Verification record and remaining checks</External></div> }
    ], next: { href: '/', label: 'Return to the observatory' }
  },
  terms: {
    eyebrow: 'Terms of use', title: 'Terms for using MetaTray.',
    intro: 'MetaTray is an experimental cortical-response observatory with a simulated account. These terms explain the service’s boundaries, user responsibilities and limits of responsibility.',
    note: 'Version 1.0 · 14 September 2026. Mandatory legal rights remain protected. These terms do not promise immunity from liability.',
    sections: [
      { id: 'scope', title: 'Scope and service operator', body: <><p>These terms apply to this MetaTray website, its public interfaces, visualizations and paper simulation. “We”, “us” and “operators” refer to the persons or entity making this deployment available. “You” means a person using the service. The source-code license and third-party licenses apply separately to their respective materials.</p><p>Please read these terms before using MetaTray. If you do not accept them, do not use the service. Whether and to what extent these terms form an enforceable agreement is governed by applicable law; merely displaying them does not displace your statutory rights.</p></> },
      { id: 'experiment', title: 'Experimental information, not advice', body: <><p>MetaTray provides experimental information and a paper simulation. It does not provide personalized investment, financial, tax, legal or medical advice, or a recommendation to buy, sell or hold an asset. A displayed result, simulated trade, chart, model value or source link is not a promise about future events.</p><p>You should independently verify information and obtain qualified advice where appropriate. We do not undertake to assess your financial circumstances, suitability, objectives or risk tolerance, and no advisory or fiduciary relationship is intended merely through access to the site.</p></> },
      { id: 'tokens', title: 'Tokens, simulations and external decisions', body: <><p>The current application does not accept trading deposits, hold user funds, request signing keys or execute financial orders. Paper balances and fills are simulations. They do not create a claim to funds, tokens, redemption, ownership, revenue, distributions or any other payment from the operators.</p><p>Any decision to obtain, hold or trade a token through a separate service is your own decision. Tokens can be illiquid, extremely volatile or lose their entire value. Real execution can differ materially from displayed or simulated results. A token’s name, appearance or association with this experiment does not establish its authenticity, safety, legality or value.</p><p>These terms describe this website. They do not remove obligations arising from an operator’s separate representations, token issuance, financial activity or other conduct.</p></> },
      { id: 'model-limits', title: 'Model and data limitations', body: <><p>Predicted cortical values are generated by a research model from authored sensory inputs. They are not measurements from a visitor or trader, proof of consciousness or emotion, or validated forecasts of prices or behavior. Demo events and default geometry are explicitly synthetic or illustrative.</p><p>Data and model output may be delayed, incomplete, inaccurate, unavailable or invalidated by a chain reorganization. Providers, networks and software can fail. You must not interpret camera motion or a refreshed interface as proof that a new model inference has completed.</p></> },
      { id: 'availability', title: 'Availability and warranties', body: <><p>Subject to the mandatory rights below, the service is provided as available for experimental use. To the extent the law allows, we do not give an additional warranty of accuracy, uninterrupted availability, security, fitness for a particular purpose, predictive performance or compatibility with your systems.</p><p>We may reasonably change, suspend or discontinue features for maintenance, security, technical or legal reasons. Where reasonably practicable, we will give notice of a material change. This provision does not permit us to avoid an existing legal obligation or deny a remedy that the law requires.</p></> },
      { id: 'liability', title: 'Limitations of liability', body: <><p>Subject to the mandatory-rights section and to the maximum extent permitted by applicable law, we exclude liability that may lawfully be excluded for loss arising from use of, inability to use, or reliance on this experimental service. This includes losses from independent external trading decisions and, where legally excludable, lost profits, missed opportunities, loss of data, business interruption and indirect or consequential loss.</p><p>These limitations are intended to benefit the deployment operators and the founders, developers, maintainers and contributors involved in providing MetaTray, only to the extent the law allows them to receive that protection. Participation in the project does not itself provide immunity or change any person’s actual legal responsibilities.</p><p>We do not exclude liability for fraud, fraudulent misrepresentation, wilful misconduct, or any other conduct or loss for which exclusion is prohibited. If an exclusion is ineffective, liability is limited only where and to the extent a lawful limitation applies. No zero-liability guarantee is made.</p></> },
      { id: 'mandatory-rights', title: 'Rights that cannot be excluded', body: <><p>Nothing in these terms excludes, restricts or modifies a consumer guarantee, statutory remedy, right or liability that cannot lawfully be excluded, restricted or modified. This includes rights under the Australian Consumer Law where it applies, and mandatory protections under other applicable laws.</p><p>These protections take priority over any inconsistent provision. A disclaimer does not make misleading conduct lawful, turn a regulated service into an unregulated one, or replace the need to comply with applicable obligations. You retain access to courts, regulators and remedies where the law provides them.</p></> },
      { id: 'acceptable-use', title: 'Responsible use', body: <><p>You must use the service lawfully and must not attempt unauthorized access, interfere with other users, distribute malicious code, evade access restrictions or misrepresent synthetic or predicted output as measured human data. Do not submit passwords, signing keys or sensitive personal information through public channels.</p><p>You remain responsible for unlawful conduct you carry out. These terms do not impose a blanket indemnity for losses caused by the operators’ own conduct. Any recovery of costs or damages must have a lawful basis.</p></> },
      { id: 'third-parties', title: 'Independent project and third-party rights', body: <><p>MetaTray is independent of Meta and other referenced research, blockchain and hosting providers. References identify upstream tools, sources or infrastructure and do not imply sponsorship or endorsement. External websites and services apply their own terms.</p><p>The TRIBE release and feature models have separate license conditions. These terms do not grant commercial model rights or override upstream licenses. Rights in original source code remain governed by the repository license.</p></> },
      { id: 'changes', title: 'Changes, applicable law and severability', body: <><p>Material revisions will be identified by an updated version or date on this page and apply prospectively to the extent permitted by law. They do not retrospectively remove accrued rights. If you do not accept a revision, you may stop using the service.</p><p>Applicable law determines your rights and the competent courts. These terms do not select an exclusive foreign forum, require arbitration, shorten a mandatory claim period or waive a protected right to bring a claim. If a provision is unenforceable, the remaining provisions continue only to the extent they can lawfully do so.</p></> },
      { id: 'contact', title: 'Questions and contact', body: <><Contact/><p>Our <Link href="/privacy">privacy notice</Link> explains the information used by the current application and the role of hosting and chain-data providers.</p></> }
    ], next: { href: '/privacy', label: 'Read the privacy notice' }
  },
  privacy: {
    eyebrow: 'Privacy', title: 'Know what the observatory uses.',
    intro: 'This notice describes the current MetaTray application. A deployment operator’s actual hosting, logging and support arrangements also determine how information is processed.',
    note: 'Version 1.0 · 14 September 2026. The website does not record your brain or ask you to connect a wallet.',
    sections: [
      { id: 'direct-input', title: 'Information you provide', body: <><p>The current interface has no account registration, identity form, payment form, wallet connection or user-media upload. You can inspect the observatory without giving the application your name, email address, seed phrase or signing key.</p><p>If you separately contact an operator or post an issue on the source repository, the information you choose to include is handled through that channel. Public repository issues are public; do not include sensitive personal information there.</p></> },
      { id: 'requests', title: 'Web requests and hosting', body: <><p>Your browser sends normal requests to load pages, fonts, scripts and read APIs. A hosting or security provider may process your IP address, request time, browser information, requested path and diagnostic or abuse-prevention records in providing its service.</p><p>The application does not add an advertising analytics SDK or custom visitor-tracking system. This does not mean the hosting environment collects no logs. The operator must check the actual provider configuration, retention periods and applicable notices for the deployed service.</p></> },
      { id: 'chain-data', title: 'Public chain observations', body: <><p>A configured indexer reads public transaction and contract-event information for the selected market. Displayed receipts can include a chain ID, contract address, transaction hash, log index, block hash, timestamp and trade amounts. Such information can sometimes be linked with other public records.</p><p>MetaTray does not infer a trader’s real-world identity or match a visitor to a wallet. Demo records are synthetic. Public blockchain records are maintained by the relevant network and cannot be erased by removing a local copy from this website.</p></> },
      { id: 'model-data', title: 'Information used by the model', body: <><p>The GPU worker constructs audiovisual inputs from recorded market observations and the paper account. Model artifacts can include generated video, narration, alignment events, predictions, provenance and processing records. They are not recordings of a website visitor or a trader’s brain.</p><p>The intended deployment runs the configured model on an operator-managed GPU service. The supplied code does not upload a visitor’s media to a hosted Meta inference API. Obtaining model dependencies and weights is a separate operator setup step.</p></> },
      { id: 'browser-storage', title: 'Browser storage and downloads', body: <><p>The current application does not set a custom tracking cookie or persist visitor preferences in local storage. UI choices such as the selected viewer tab are held in the current page session. Fonts are served with the application rather than requested from a remote font service.</p><p>A receipt export is generated in your browser and downloaded to your device. The export action does not itself upload that file to a sharing service. If you later share a receipt, review its contents first. Infrastructure providers may use separate security mechanisms under their own policies.</p></> },
      { id: 'retention', title: 'Retention, recipients and rights', body: <><p>Recorded market data, jobs and predictions are stored in the operator’s database, with generated media and raw outputs on worker storage. The source does not impose a universal deletion schedule. Retention depends on the operator’s configuration and legal obligations.</p><p>Hosting, database, RPC and GPU providers may process information needed to deliver their services and may operate in different countries. The operator must identify its actual providers, locations and retention practices when deploying the service. The source contains no sale-of-personal-data integration.</p><p>Depending on applicable law, you may have rights to access, correct, delete or object to processing of personal information. These rights have legal limits and cannot remove immutable public blockchain history. Contact the deployment operator through a private channel for a request.</p></> },
      { id: 'contact', title: 'Contact and notice changes', body: <><Contact/><p>Changes to the application’s data practices should be reflected in this notice before those practices are introduced. The version and date above identify the current notice. See the <Link href="/terms">terms of use</Link> for the service’s experimental scope.</p></> }
    ], next: { href: '/about', label: 'Learn more about MetaTray' }
  }
};
